# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'abc-skree'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["skreecustom_left","skreecustom_right"]'
      modules: '["chadgpt-o1/ZMK-XIAOv4-Std/NS-3x5+3+1TB"]'
